# -*- coding: utf-8 -*-
"""logistic_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xb6wvRmpKXOOgSil2wXl8Cco3lFt6d51
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

dt=pd.read_csv("/content/gdrive/MyDrive/weatherAUS.csv")

dt.head()

#REMOVING THE OBJECTS WHICH ARE OF NO USES
dt.drop(['Date', 'Location','Humidity9am', 'WindGustDir','Pressure9am', 'WindDir9am','WindGustSpeed', 'WindDir3pm'], axis=1, inplace=True)
dt.head()

#FILLING THE MEAN VALUE IN LACE OF NAN
dt.fillna(dt.mean(),inplace=True)
dt.head()

#CONVERTING IT INTO BINARY DIGIT FOR LOGISTIC REGRESSION
dt.RainToday = [1 if each == 'Yes' else 0 for each in dt.RainToday]
dt.RainTomorrow = [1 if each == 'Yes' else 0 for each in dt.RainTomorrow]
dt.sample(3)

#SELECTING X & Y VALUES
x=dt.drop("RainTomorrow",axis=1)
y=dt["RainTomorrow"]
x.astype(int)
y.astype(int)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_train)
y_pred

y_pred.shape

lr.predict_proba(x_test)

lr.score(x_train,y_train)

lr.score(x_test,y_test)

