# -*- coding: utf-8 -*-
"""logistic_moderate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FbMOzp5hwaSB0T9fl6rg2FmeLZ6AyhfY
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive

drive.mount('/content/gdrive')

dt=pd.read_csv("/content/gdrive/MyDrive/train.csv")
dt.head()

dt.info()

dt.isnull().sum()

dt.drop('Cabin',axis=1,inplace=True)
dt.head()

dt.dropna(inplace=True)
dt

dt.info()

sex=pd.get_dummies(dt["Sex"],drop_first=True)   #method to make coloumns that we require and drop_first remove the the first coloumn

emb=pd.get_dummies(dt["Embarked"],drop_first=True)

con=pd.concat([dt,sex,emb],axis=1)
con.head()

con=con.drop(["PassengerId","Pclass","Name","Sex","SibSp","Ticket","Embarked"],axis=1,inplace=True)  #method to drop multile items

dt.head()

x=dt.drop("Survived",axis=1)
y=dt["Survived"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.3, random_state=0)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score

lr=LogisticRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

r2_score(y_test,y_pred)

from sklearn.metrics import classification_report as cr
# Method for checking the accuracy of Predicted value

cr(y_test,y_pred)

from sklearn.metrics import confusion_matrix as cm

cm(y_test,y_pred)

from sklearn.metrics import accuracy_score as s

s(y_test,y_pred)

