# -*- coding: utf-8 -*-
"""lr_normal equation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y3W4XW24NTjemE5-MwsmvjrcXrNqJeFa
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive

drive.mount('/content/gdrive')

dt=pd.read_csv("/content/gdrive/MyDrive/Salary_Data.csv")

dt.head()

x=dt["YearsExperience"]
y=dt["Salary"]
plt.scatter(x,y)
plt.show()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.3, random_state=0)

num=(x_train*y_train).mean()-x_train.mean()*y_train.mean()
den=(x_train**2).mean()-x_train.mean()**2

m=num/den

c=y_train.mean()-m*x_train.mean()

m,c

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score

lr=LogisticRegression()

lr.fit(x_train.values.reshape(-1,1),y_train.values.reshape(-1,1))

y_pred=m*x + c

plt.scatter(x,y,c="red")
plt.plot(x,y_pred)
plt.grid()
plt.pause(1)
plt.show()

